[template]
src = ".env.tmpl"
dest = "/app/.env"
keys = [
    "/{{ .Env.NAMESPACE }}/mongo",
    "/{{ .Env.NAMESPACE }}/port"
]
check_cmd = "/usr/local/bin/confd -onetime"
reload_cmd = "supervisorctl restart node"