[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
loglevel=DEBUG

[program:confd]
command=confd -onetime -confdir /etc/confd -backend ssm
autostart=true
autorestart=false
startretries=3

[program:node]
command=node server.js
directory=/app
autostart=true
autorestart=true
startretries=3
depends_on=confd
