[supervisord]
nodaemon=true

[program:confd]
command=/usr/local/bin/confd -onetime -confdir /etc/confd
autostart=true
autorestart=false
startretries=0

[program:node]
command=node server.js
directory=/app
autostart=true
autorestart=true
startretries=3
depends_on=confd